import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import React from "react";

import { StoreProvider } from "@/store/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MeepShop Frontend Homework",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  messages,
  conversations,
}: Readonly<{
  children: React.ReactNode;
  messages: React.ReactNode;
  conversations: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <main className="container mx-auto flex h-full gap-10 py-10">
            <section className="hidden md:block">{conversations}</section>
            <section className="bg-background-higher hidden grow md:block">
              {messages}
            </section>
            <section className="block md:hidden">{children}</section>
          </main>
        </StoreProvider>
      </body>
    </html>
  );
}
