import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/store/provider";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MeepShop Frontend Homework",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  messages,
  conversations,
}: Readonly<{
  children: React.ReactNode;
  messages: React.ReactNode;
  conversations: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <main className="container mx-auto py-10 flex gap-10 h-full">
            <section className="md:block hidden">{conversations}</section>
            <section className="grow md:block hidden bg-background-higher">
              {messages}
            </section>
            <section className="md:hidden block">{children}</section>
          </main>
        </StoreProvider>
      </body>
    </html>
  );
}
